import { motion } from "framer-motion";
import { Info } from "lucide-react";

const AIDisclaimer = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ delay: 1 }}
      className="mt-12 p-4 rounded-xl bg-muted/30 border border-border/50"
    >
      <div className="flex gap-3">
        <Info className="w-5 h-5 text-muted-foreground flex-shrink-0 mt-0.5" />
        <div>
          <h4 className="font-semibold font-mono text-sm text-foreground mb-1">AI Evaluation Disclaimer</h4>
          <p className="text-xs text-muted-foreground leading-relaxed">
            This analysis is generated by AI and may not capture all nuances of code quality. 
            AI-based evaluation has inherent limitations including potential false positives/negatives, 
            inability to fully understand business context, and limited assessment of runtime behavior. 
            <span className="text-foreground font-medium"> Human review is strongly recommended for final judgment</span>, 
            especially for production deployments and hiring decisions.
          </p>
        </div>
      </div>
    </motion.div>
  );
};

export default AIDisclaimer;
